inputs:
  - "data/sample_data/*.nd2"   # files, globs, or directories

output_root: "results"

channels:
  egfp_keywords: ["egfp", "gfp"]
  nuc_keywords:  ["bfp", "sgbfp", "dapi", "nuc"]

preprocessing:
  projection: "max"   # required; only 'max' supported

# Legacy plugin/aggregation keys removed in projection-only mode.
